### ISSUE TITLE
Request: Toggle for only in PvP Areas

### ISSUE THREAD

**Issue by rsValliance** [LuxOG/logouttimer#5]
Love the plugin idea. Would be awesome if there was an ability to toggle it to only show when in PvP areas, like with the Player Indicators plugin.

Also possibly options for more "obvious" timers / alerts when you're able to logout, similar to Thrall timer and such.

**Comment by LuxOG** [comment]
I'm adding an option to display only in pvp. However I don't plan to add a notification, the use case I had in mind when creating this plugin was vetion, not getting gap on somebody
