### ISSUE TITLE
Infobox pops up twice

### ISSUE THREAD

**Issue by YvesW** [LuxOG/logouttimer#8]
Steps to reproduce:
1. Go to the wilderness dungeon with fire giants (Guthixian symbol). Haven't tested at other locations yet, but also happened at the hellhounds north of the resource area.
2. Get attacked by a fire giant

![afbeelding](https://github.com/LuxOG/logouttimer/assets/7929021/6117095c-9a41-4ef1-afb2-cdc80e0e0d74)

**Comment by LuxOG** [comment]
The timer for logging out after combat and hopping worlds is slightly different. I added both options in the config, you probably have both turned on at once.

**Comment by ShaunDreclin** [comment]
Came here to report the same issue; a different icon and tooltip for each infobox would help reduce confusion
